<a href="https://colab.research.google.com/github/udeigwe/pytorch_tutorial/blob/main/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### AUTOGRAD: AUTOMATIC DIFFERENTIATION

In [2]:
import torch

#Create a tensor and set requires_grad=True 
# to track computation with it
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
#Do a tensor operation:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
# y was created as a result of an operation, so it has a grad_fn
print(y.grad_fn)


In [7]:
# Do more operations on y
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. 
# The input flag defaults to False if not given.

a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True
