<a href="https://colab.research.google.com/github/udeigwe/pytorch_tutorial/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro To Pytorch 1




In [ ]:
from __future__ import print_function
import torch

In [ ]:
x = torch.empty(5,3) #Construct a 5x3 matrix, uninitialized:
print(x)

tensor([[4.2923e-35, 0.0000e+00, 1.3571e+28],
        [1.7258e+25, 1.2077e+33, 2.6908e+20],
        [2.9758e+29, 2.6219e+20, 1.8524e+28],
        [7.5031e+28, 6.9776e+22, 6.7121e-07],
        [4.1486e-08, 1.0299e-11, 3.5674e-41]])


In [ ]:
x = torch.rand(5,3) #Construct a randomly initialized matrix:
print(x)


tensor([[0.8648, 0.5652, 0.0966],
        [0.4120, 0.5201, 0.8209],
        [0.1810, 0.4284, 0.3114],
        [0.2737, 0.4763, 0.1196],
        [0.5918, 0.5737, 0.2426]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
#Construct a tensor directly from data:
x = torch.tensor([5.5, 3]) 
print(x)

tensor([5.5000, 3.0000])


In [ ]:
#create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double) 
# new_* methods take in sizes
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
# override dtype!
x = torch.randn_like(x, dtype=torch.float) 
print(x) 
# result has the same size

tensor([[-0.5265,  0.5548, -0.9632],
        [ 0.6938, -1.0407, -2.6610],
        [ 0.2599,  0.7251,  0.6694],
        [ 0.7456,  0.7055, -0.9831],
        [-1.1002,  0.1346, -1.4417]])


In [ ]:
# Get its size:
print(x.size())

torch.Size([5, 3])


### Operations

In [ ]:
#addition -- syntax 1
y = torch.rand(5,3)
print(x+y)

tensor([[-0.4827,  1.2482, -0.6567],
        [ 1.4953, -0.9978, -2.0027],
        [ 0.8277,  1.4551,  1.5901],
        [ 1.2576,  1.5588, -0.6706],
        [-0.7721,  0.9579, -0.9394]])


In [ ]:
#addition -- syntax 2
print(torch.add(x, y))

tensor([[-0.4827,  1.2482, -0.6567],
        [ 1.4953, -0.9978, -2.0027],
        [ 0.8277,  1.4551,  1.5901],
        [ 1.2576,  1.5588, -0.6706],
        [-0.7721,  0.9579, -0.9394]])


In [ ]:
# providing an output tensor as argument -- syntax 3
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4827,  1.2482, -0.6567],
        [ 1.4953, -0.9978, -2.0027],
        [ 0.8277,  1.4551,  1.5901],
        [ 1.2576,  1.5588, -0.6706],
        [-0.7721,  0.9579, -0.9394]])


In [ ]:
# adds x to y -- syntax 4
y.add_(x)
print(y)

tensor([[-0.4827,  1.2482, -0.6567],
        [ 1.4953, -0.9978, -2.0027],
        [ 0.8277,  1.4551,  1.5901],
        [ 1.2576,  1.5588, -0.6706],
        [-0.7721,  0.9579, -0.9394]])


Note: Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [ ]:
print(x[:,1])

tensor([ 0.5548, -1.0407,  0.7251,  0.7055,  0.1346])


In [ ]:
# If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
print(x)

tensor([[ 0.1881, -0.7081, -0.3245,  0.1548],
        [ 0.9866,  0.1113, -0.7331,  0.6774],
        [ 0.9803,  0.1498,  0.1074, -1.7490],
        [ 0.5579, -0.4199, -0.2811, -1.0627]])


In [ ]:
y = x.view(16)
print(y)


tensor([ 0.1881, -0.7081, -0.3245,  0.1548,  0.9866,  0.1113, -0.7331,  0.6774,
         0.9803,  0.1498,  0.1074, -1.7490,  0.5579, -0.4199, -0.2811, -1.0627])


In [ ]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)

tensor([[ 0.1881, -0.7081, -0.3245,  0.1548,  0.9866,  0.1113, -0.7331,  0.6774],
        [ 0.9803,  0.1498,  0.1074, -1.7490,  0.5579, -0.4199, -0.2811, -1.0627]])


In [ ]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy Bridge

##### Converting a Torch Tensor to a NumPy Array

In [ ]:
#Converting a Torch Tensor to a NumPy Array

a= torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Converting NumPy Array to Torch Tensor

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [ ]:
print(z)

tensor([[ 0.1881, -0.7081, -0.3245,  0.1548,  0.9866,  0.1113, -0.7331,  0.6774],
        [ 0.9803,  0.1498,  0.1074, -1.7490,  0.5579, -0.4199, -0.2811, -1.0627]])
