<a href="https://colab.research.google.com/github/udeigwe/pytorch_tutorial/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro To Pytorch 1




In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3) #Construct a 5x3 matrix, uninitialized:
print(x)

tensor([[1.2577e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 4.7270e-36]])


In [3]:
x = torch.rand(5,3) #Construct a randomly initialized matrix:
print(x)


tensor([[0.2701, 0.5192, 0.0432],
        [0.9235, 0.9720, 0.4633],
        [0.8429, 0.1188, 0.3122],
        [0.4407, 0.6742, 0.0691],
        [0.9572, 0.3377, 0.9809]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#Construct a tensor directly from data:
x = torch.tensor([5.5, 3]) 
print(x)

tensor([5.5000, 3.0000])


In [6]:
#create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double) 
# new_* methods take in sizes
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# override dtype!
x = torch.randn_like(x, dtype=torch.float) 
print(x) 
# result has the same size

tensor([[ 0.3267, -2.5566, -1.6583],
        [-0.0174, -0.5936, -0.7456],
        [-0.1317,  0.2532, -0.5447],
        [ 0.4672,  0.7333, -0.3549],
        [-0.3527,  0.9021,  1.1750]])


In [8]:
# Get its size:
print(x.size())

torch.Size([5, 3])


### Operations

In [9]:
#addition -- syntax 1
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.6339, -2.2152, -1.0605],
        [ 0.2632, -0.3237, -0.6652],
        [ 0.1264,  0.8003, -0.5426],
        [ 1.4276,  0.8002,  0.1425],
        [-0.2581,  1.7385,  2.1066]])


In [10]:
#addition -- syntax 2
print(torch.add(x, y))

tensor([[ 0.6339, -2.2152, -1.0605],
        [ 0.2632, -0.3237, -0.6652],
        [ 0.1264,  0.8003, -0.5426],
        [ 1.4276,  0.8002,  0.1425],
        [-0.2581,  1.7385,  2.1066]])


In [11]:
# providing an output tensor as argument -- syntax 3
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6339, -2.2152, -1.0605],
        [ 0.2632, -0.3237, -0.6652],
        [ 0.1264,  0.8003, -0.5426],
        [ 1.4276,  0.8002,  0.1425],
        [-0.2581,  1.7385,  2.1066]])


In [12]:
# adds x to y -- syntax 4
y.add_(x)
print(y)

tensor([[ 0.6339, -2.2152, -1.0605],
        [ 0.2632, -0.3237, -0.6652],
        [ 0.1264,  0.8003, -0.5426],
        [ 1.4276,  0.8002,  0.1425],
        [-0.2581,  1.7385,  2.1066]])


Note: Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [13]:
print(x[:,1])

tensor([-2.5566, -0.5936,  0.2532,  0.7333,  0.9021])


In [14]:
# If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
print(x)

tensor([[ 0.7045,  1.0545, -2.1450,  1.2747],
        [-0.9232, -0.7119,  0.5889, -1.9858],
        [-0.0884, -2.4562, -0.1763,  0.4223],
        [-1.9431,  0.7589, -0.0087,  0.1290]])


In [15]:
y = x.view(16)
print(y)


tensor([ 0.7045,  1.0545, -2.1450,  1.2747, -0.9232, -0.7119,  0.5889, -1.9858,
        -0.0884, -2.4562, -0.1763,  0.4223, -1.9431,  0.7589, -0.0087,  0.1290])


In [16]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)

tensor([[ 0.7045,  1.0545, -2.1450,  1.2747, -0.9232, -0.7119,  0.5889, -1.9858],
        [-0.0884, -2.4562, -0.1763,  0.4223, -1.9431,  0.7589, -0.0087,  0.1290]])


In [17]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy Bridge

##### Converting a Torch Tensor to a NumPy Array

In [18]:
#Converting a Torch Tensor to a NumPy Array

a= torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Converting NumPy Array to Torch Tensor

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [23]:
print(z)

tensor([[ 0.7045,  1.0545, -2.1450,  1.2747, -0.9232, -0.7119,  0.5889, -1.9858],
        [-0.0884, -2.4562, -0.1763,  0.4223, -1.9431,  0.7589, -0.0087,  0.1290]])
